site:
  title: Fleet
  url: /
  start_page: v0.12@fleet:en:index.adoc

content:
  sources:
    - url: https://github.com/rancher/fleet-product-docs.git
      start_paths: [versions/v0.12, versions/v0.11, versions/v0.10, versions/v0.9]
      branches: [main]

# Description: SUSE UI bundle
ui:
  bundle:
    url: ./style-bundle/community-ui-bundle.zip #https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true

runtime:
  fetch: true

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'

output:
  dir: build/site
