site:
  title: Fleet
  url: /
  start_page: next@fleet:index.adoc

content:
  sources:
    - url: ./
      start_paths: [versions/next, versions/v0.12]
      branches: HEAD

# Description: SUSE UI bundle
ui:
  bundle:
    url: ./dsc-style-bundle/ui-bundle.zip
    snapshot: true
  supplemental_files: ./turtles-supplemental-files


runtime:
  fetch: true

asciidoc:
  attributes:
    page-pagination: ''
    build-type: community
    page-toclevels: 4@
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'

output:
  dir: build/site-community
