site:
  title: Fleet
  url: /
  start_page: v0.12@Fleet:en:index.adoc

content:
  sources:
    - url: ./
      start_paths: [versions/v0.12, versions/v0.11, versions/v0.10, versions/v0.9]
      branches: HEAD

# Description: SUSE UI bundle
ui:
  bundle:
    url: ./style-bundle/product-ui-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: '@springio/antora-xref-extension'

output:
  dir: build/site